name: amiibo_network
description: An Amiibo collection app designed to allow you to keep track of
  which Amiibo are in your collection.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.1+97

environment:
  sdk: ^3.9.2
  flutter: 3.35.7

publish_to: none
dependencies:
  collection: ^1.18.0
  dio: ^5.9.0
  drift: ^2.28.1
  drift_sqflite: ^2.0.1
  dynamic_color:
    git:
      url: https://github.com/EdwynZN/flutter-packages.git
      ref: patch-1
      path: packages/dynamic_color
  equatable: ^2.0.7
  file_picker: 10.3.1
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_remote_config: ^6.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.1.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^3.0.0
  intl_utils: ^2.8.11
  json_annotation: ^4.9.0
  launch_app_store: ^1.1.4
  loading_animation_widget: ^1.3.0
  material_color_utilities: ^0.11.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  sliver_tools: ^0.2.12
  sqflite: ^2.4.1
  sqlite3_flutter_libs: ^0.5.39
  stash: ^5.1.0
  stash_dio: ^5.1.0
  stash_hive: ^5.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.22.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/text/
    - assets/images/
    - assets/icons/
    - assets/game_icons/
    - assets/collection/
    - assets/databases/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
